package common

import (
	"regexp"
	"strings"
)

var logTextChineseMap = strings.NewReplacer(
	"金额", "amount",
	"额度", "quota",
	"点额度", "quota points",
	"任务", "task",
	"任务数", "task count",
	"渠道", "channel",
	"请求", "request",
	"订单", "order",
	"订单状态", "order status",
	"支付", "payment",
	"支付方式", "payment method",
	"支付成功", "payment success",
	"支付失败", "payment failed",
	"充值", "top up",
	"兑换码", "redemption code",
	"交易", "transaction",
	"签名", "signature",
	"验证", "verify",
	"验证失败", "verification failed",
	"验证成功", "verification passed",
	"回调", "callback",
	"回调事件", "callback event",
	"回调处理", "callback handling",
	"读取", "read",
	"参数", "param",
	"创建", "create",
	"创建成功", "created",
	"已创建", "created",
	"新增", "create",
	"更新", "update",
	"更新成功", "updated",
	"更新失败", "update failed",
	"更新订单", "update order",
	"更新用户", "update user",
	"余额", "balance",
	"失败", "failed",
	"成功", "success",
	"忽略", "skip",
	"缺少", "missing",
	"不存在", "not found",
	"未找到", "not found",
	"异常", "error",
	"错误", "error",
	"超时", "timeout",
	"超出", "exceeded",
	"超长", "overflow",
	"过高", "too high",
	"过低", "too low",
	"已使用", "used",
	"已过期", "expired",
	"预扣费", "pre-charged quota",
	"补扣费", "recharge by deficit",
	"返还", "refund",
	"返还", "refund",
	"剩余", "remaining",
	"用户", "user",
	"令牌", "token",
	"模型", "model",
	"分组", "group",
	"流量", "traffic",
	"上限", "limit",
	"下线", "disable",
	"启用", "enable",
	"关闭", "disabled",
	"开启", "enable",
	"保存", "save",
	"生成", "generate",
	"发送", "send",
	"通知", "notification",
	"提醒", "alert",
	"限额", "quota limit",
	"用尽", "exhausted",
	"不足", "insufficient",
	"不足以", "insufficient",
	"未配置", "not configured",
	"未启用", "not enabled",
	"未授权", "unauthorized",
	"非法", "invalid",
	"无效", "invalid",
	"空", "empty",
	"空值", "null",
	"无权", "not permitted",
	"邮箱", "email",
	"验证码", "verification code",
	"新用户", "new user",
	"邀请码", "invite code",
	"注册", "register",
	"签到", "check-in",
	"赠送", "grant",
	"赠", "grant",
	"预警", "warning",
	"剩余额度", "remaining quota",
	"当前", "current",
	"原生", "raw",
	"总额度", "total quota",
	"原始", "raw",
	"日志", "log",
	"记录", "record",
	"记录失败", "record failed",
	"预留", "reserved",
	"保留", "reserve",
	"状态", "status",
	"结果", "result",
	"原因", "reason",
	"原因：", "reason:",
	"原因:", "reason:",
	"其余", "remaining",
	"显示", "display",
	"全部", "all",
	"详情", "details",
	"配置", "settings",
	"配置项", "settings",
	"配置成功", "settings updated",
	"参数错误", "invalid params",
	"非法参数", "invalid params",
	"未完成", "incomplete",
	"完成", "done",
	"完成支付", "payment complete",
	"文件", "file",
	"路径", "path",
	"数量", "count",
	"时间", "time",
	"分钟", "minutes",
	"秒", "s",
	"版本", "version",
	"事件", "event",
	"价格", "price",
	"比率", "ratio",
	"倍率", "multiplier",
	"服务", "service",
	"安全", "security",
	"校验", "check",
	"校验失败", "verification failed",
	"解析", "parse",
	"解析失败", "parse failed",
	"处理", "handle",
	"处理失败", "handle failed",
	"处理成功", "handled",
	"跳过", "skip",
	"预留", "reserve",
	"退款", "refund",
	"重试", "retry",
	"重试次数", "retry count",
	"并", "and",
	"及", "and",
	"或", "or",
	"和", "and",
)

var logTextChinesePattern = regexp.MustCompile(`[\p{Han}]+`)

func SanitizeLogText(s string) string {
	if s == "" {
		return s
	}

	s = logTextChineseMap.Replace(s)
	s = logTextChinesePattern.ReplaceAllString(s, "")
	s = strings.Join(strings.Fields(s), " ")
	return s
}
